name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      # gradle 권한 오류 체크 
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
        
      # gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar
    
      # Spring 어플리케이션 Docker Image 빌드
      - name: Build Docker Image For Spring
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-default-jdk11 .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-default-jdk11
        
        
        ## deploy to ec2
      - name: Deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-default-jdk11
            docker stop server
            docker rm server
            docker run -it -d -p 80:8080 --name server ${{ secrets.DOCKER_USERNAME }}/spring-boot-default-jdk11
